language: python

python:
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"
  - "nightly"

install:
  - pip install -r requirements.txt

# just run the tests first
script:
  - python -m unittest discover tests

# if the tests succeed, then run full coverage reports
after_success:
  # rerun tests with coverage
  - pip install coverage
  - coverage run --source pymcutil -m unittest discover tests
  # upload to codecov
  - pip install codecov
  - codecov
