import abc

from pymcutil.resource.function import Function
from pymcutil.resource.resource_generator.abc.resource_generator import ResourceGenerator
from pymcutil.resource.resource_location.function_location import FunctionLocation


class FunctionGenerator(ResourceGenerator):
    @abc.abstractmethod
    def location(self, *params) -> FunctionLocation:
        """ Return a `FunctionLocation` for the resource that would be generated by the given parameters. """

    @abc.abstractmethod
    def generate(self, *params) -> Function:
        """ Return a `Function` generated using the given parameters."""
