import abc

from pymcutil.resource.function_resource import FunctionResource
from pymcutil.resource.resource_generator.abc.resource_generator import ResourceGenerator
from pymcutil.resource.resource_location.function_location import FunctionLocation
from pymcutil.resource.resource_reference.function_reference import FunctionReference
from pymcutil.resource.resource_manager.standard_resource_manager import ResourceManager


class FunctionGenerator(ResourceGenerator):
    @abc.abstractmethod
    def location(self, manager: ResourceManager, reference: FunctionReference) -> FunctionLocation:
        """ Return a `FunctionLocation` for the function that would be generated by the given `FunctionReference`. """

    @abc.abstractmethod
    def generate(self, manager: ResourceManager, reference: FunctionReference) -> FunctionResource:
        """ Return a `Function` generated using the given `FunctionReference`."""
