import abc

from pymcutil.resource.abc.resource import Resource
from pymcutil.resource.resource_location.abc.resource_location import ResourceLocation


class ResourceGenerator(abc.ABC):
    @abc.abstractmethod
    def location(self, *params) -> ResourceLocation:
        """ Return a `ResourceLocation` for the resource that would be generated by the given parameters. """

    @abc.abstractmethod
    def generate(self, *params) -> Resource:
        """ Return a `Resource` generated using the given parameters."""
